stomp.settings:
    type: config_object
    label: 'Stomp settings'
    mapping:
      brokers:
        type: sequence
        label: 'Brokers'
        sequence:
          type: string
          label: 'Broker'
